### ISSUE TITLE
Can't access webui after starting Kapowarr container via Podman

### ISSUE THREAD

**Issue by seannymurrs** [Casvt/Kapowarr#186]
**Description of the bug**

I'm attempting to run Kapowarr via podman and a docker-compose.yml file. I can start the container up just fine (I don't get any errors), but I get a connection lost message when trying to access the webui. I'm not sure how to diagnose the issue further.

**To Reproduce**

Here is my docker-compose.yml file contents:

```
version: "3.3"
services:
  kapowarr:
    container_name: kapowarr
    image: mrcas/kapowarr:latest
    volumes:
      - "/home/seannymurrs/Kapowarr/db:/app/db"
      - "/home/seannymurrs/Downloads/kapowarr_temp:/app/temp_downloads"
      - "/home/seannymurrs/comics:/comics-1"
    ports:
      - 35656:5656
```

**Expected behaviour**

I would expect to be able to access the webui when navigating to http://serveraddress:35656 (actual server address redacted).

**Additional context**

I'm attempting to install/run Kapowarr on a remote seedbox (Whatbox) that I don't have root access on (which is why I'm using Podman).
