### ISSUE TITLE
Updating Volumes bug

### ISSUE THREAD

**Issue by JoshuaAJones74** [Casvt/Kapowarr#39]
**Description of the bug**

Gets stuck after running Update All task
**To Reproduce**

1. Open Kapowarr
2. See error

**Expected behaviour**

Update completes.
**Screenshots**

[2023-05-30 00:20:38][Thread-1][INFO] Added task: Update All (1)
[2023-05-30 00:20:38][Task Handler][INFO] Finished task Update All
[2023-05-30 01:20:39][Thread-2][INFO] Added task: Update All (1)
[2023-05-30 01:20:39][Task Handler][ERROR] An error occured while trying to run a task: 
Traceback (most recent call last):
  File "/app/backend/tasks.py", line 293, in __run_task
    result = task.run()
  File "/app/backend/tasks.py", line 229, in run
    refresh_and_scan()
  File "/app/backend/volumes.py", line 444, in refresh_and_scan
    scan_files(Volume(volume[0]).get_info())
  File "/app/backend/files.py", line 418, in scan_files
    file_id = _add_file(file)
  File "/app/backend/files.py", line 344, in _add_file
    cursor.execute(
sqlite3.OperationalError: database is locked
[2023-05-30 02:20:40][Thread-3][INFO] Added task: Update All (2)
[2023-05-30 03:20:41][Thread-4][INFO] Added task: Update All (3)
[2023-05-30 04:20:41][Thread-5][INFO] Added task: Update All (4)
[2023-05-30 05:20:42][Thread-6][INFO] Added task: Update All (5)
...
**Version info**
v1.0.0-beta-1
Unraid

**Additional context**
Just started using the program so I only have 2 volumes.  I am waiting to add more once a few other issues are fixed.

**Comment by Eamourinho** [comment]
Happens to me all the time too. Only fix has been to restart the container and hope that nothing locks the DB again.

Snippet from my docker-compose:
```
  kapowarr:
    container_name: kapowarr
    image: 'mrcas/kapowarr:latest'
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - '${ARRDIR}/kapowarr/db:/app/db'
      - '${ARRDIR}/kapowarr/downloads:/app/temp_downloads'
      - '${ARRDIR}/kapowarr/content:/content'
    networks:
      - reverseproxy
    restart: unless-stopped
```
